WOZ_REQUIREMENTS = [
    {
        "code": 1,
        "category": "сухая_каша_и_крахмалистые_продукты",
        "energy_value": "≥80 ккалне регламентировано100 г",
        "sodium": "≤50 мгне регламентировано100 ккал",
        "total_sugar": "не регламентировано",
        "added_sweetener": "Нет",
        "total_fat": "≤5,5 г",
        "trans_fats": "≤4,5 г или ≤3,3 г",
        "fruit_content": "≤10% сухого веса",
        "best_before_date": "6-36",
        "high_sugar_indication": "≥30%",
    },
    {
        "code": 2,
        "category": "молочные_продукты",
        "energy_value": "≥60 ккал",
        "sodium": "≤50 (100, если в названии сыр)",
        "total_sugar": "не регламентировано",
        "added_sweetener": "Нет",
        "total_fat": "не регламентировано",
        "trans_fats": "≤4,5 г",
        "fruit_content": "≤5% (макс. 2% сухих)",
        "best_before_date": "6-36",
        "high_sugar_indication": "≥40%",
    },
    {
        "code": 3.1,
        "category": "фруктовые_и_овощные_пюре/коктейли_и_фруктовые_десерты",
        "energy_value": "≥60 ккал",
        "sodium": "≤50",
        "total_sugar": "не регламентировано",
        "added_sweetener": "Нет",
        "total_fat": "не регламентировано",
        "trans_fats": "≤4,5 г",
        "fruit_content": "не регламентировано",
        "best_before_date": "6-36 (6-12 для пюре)",
        "high_sugar_indication": "≥30%",
    },
    {
        "code": 3.2,
        "category": "не регламентировано",
        "energy_value": "≤25% добавленной воды",
        "sodium": "≤50",
        "total_sugar": "не регламентировано",
        "added_sweetener": "Нет",
        "total_fat": "не регламентировано",
        "trans_fats": "≤4,5 г",
        "fruit_content": "Нет",
        "best_before_date": "6-36 (6-12 для пюре)",
        "high_sugar_indication": "≥30%",
    },
    {
        "code": 4.1,
        "category": "полукомбинированные_продукты/блюда: сочетания_крахмалистых_(крупатых)_продуктов,_овощей",
        "energy_value": "≥60 ккал",
        "sodium": "≤50",
        "total_sugar": "≤15%",
        "added_sweetener": "Нет",
        "total_fat": "≥3 г ≥8%",
        "trans_fats": "≤4,5 г",
        "fruit_content": "≤5% (макс. 2% сухих)",
        "best_before_date": "6-36 (6-12 для пюре)",
        "high_sugar_indication": "не регламентировано",
    },
    {
        "code": 4.2,
        "category": "полукомбинированные_продукты/блюда: сочетания_крахмалистых_(крупатых)_продуктов,_овощей",
        "energy_value": "≥60 ккал",
        "sodium": "≤100",
        "total_sugar": "≤15%",
        "added_sweetener": "Нет",
        "total_fat": "≥3 г ≥10%",
        "trans_fats": "≤6 г",
        "fruit_content": "≤5% (макс. 2% сухих)",
        "best_before_date": "6-36 (6-12 для пюре)",
        "high_sugar_indication": "не регламентировано",

    },
    {
        "code": 4.3,
        "category": "молочных_продуктов_и/или_белка2",
        "energy_value": "≥60 ккал",
        "sodium": "≤50 (100, если в названии сыр)",
        "total_sugar": "≤15%",
        "added_sweetener": "Нет",
        "total_fat": "≥3 г ≥8%",
        "trans_fats": "≤4,5 г",
        "fruit_content": "≤5% (макс. 2% сухих)",
        "best_before_date": "6-36 (6-12 для пюре)",
        "high_sugar_indication": "не регламентировано",
    },
    {
        "code": 4.4,
        "category": "к_источником_белка_относится_любые_виды_мяса,_мясных_субпродуктов,_птицы_или_рыбы",
        "energy_value": "≥60 ккал",
        "sodium": "≤50 (100, если в названии сыр)",
        "total_sugar": "≤15%",
        "added_sweetener": "Нет",
        "total_fat": "≥4 г ≥10%",
        "trans_fats": "≤6 г",
        "fruit_content": "≤5% (макс. 2% сухих)",
        "best_before_date": "6-36 (6-12 для пюре)",
        "high_sugar_indication": "не регламентировано",
    },
    {
        "code": 4.5,
        "category": "к_источником_белка_относится_любые_виды_мяса,_мясных_субпродуктов,_птицы_или_рыбы",
        "energy_value": "≥60 ккал",
        "sodium": "≤50",
        "total_sugar": "≤15%",
        "added_sweetener": "Нет",
        "total_fat": "≥7 г ≥40%",
        "trans_fats": "≤6 г",
        "fruit_content": "≤5% (макс. 2% сухих)",
        "best_before_date": "6-36 (6-12 для пюре)",
        "high_sugar_indication": "не регламентировано",
    },
    {
        "code": 5.1,
        "category": "сухие_закуски_и_перекусы",
        "energy_value": "≤50 ккал на порцию",
        "sodium": "≤50",
        "total_sugar": "не регламентировано",
        "added_sweetener": "Нет",
        "total_fat": "не регламентировано",
        "trans_fats": "≤4,5 г",
        "fruit_content": "100%",
        "best_before_date": "6-36",
        "high_sugar_indication": "≥30% (только сухофрукты)",
    },
    {
        "code": 5.2,
        "category": "сухие_закуски_и_перекусы",
        "energy_value": "≤50 ккал на порцию",
        "sodium": "←50",
        "total_sugar": "≤15%",
        "added_sweetener": "Нет",
        "total_fat": "≤5,5 г (если_печенье_содержит_молоко)12,13",
        "trans_fats": "≤4,5",
        "fruit_content": "не регламентировано",
        "best_before_date": "6-36",
        "high_sugar_indication": "не регламентировано",
    },
]